apiKey: NRAK-...
accountId: ""

channel:
  createChannel:
  # Set to true to enable the channel creation.
    enabled: true
  name: channel
  type: slack
  region: US
  links:
    policyNames: 
      # - policy1
      # - policy2
      # - policy3
  configuration:
  # Webhook of the slack channel
    url: ""

policy:
  createPolicy:
  # Set to true to enable the policy creation.
    enabled: true
  name: policy
  incidentPreference: PER_POLICY
  region: US
  conditions:
  # Create one or more alert conditions at policy creation.
    - name: testcond
      type: NRQL
      nrql:
        query: SELECT count(*) FROM Transactions
        evaluationOffset: 10
      enabled: true
      terms:
        threshold: 75.0
        threshold_occurrences: ALL
        threshold_duration: 60
        priority: CRITICAL
        operator: ABOVE
      violationTimeLimit: ONE_HOUR
      valueFunction: SINGLE_VALUE

# The alertCondition is used to create alerts in existing policies. To create alerts in a new policy, 
# managed by the operator, use the conditions section at "policy".
alertCondition:
  createAlertCondition:
  # Set to true to enable the creation of alerts in existing policies.
    enabled: true
  conditions:
    # - name: testCondition
    #   type: NRQL
    #   nrql:
    #     query: SELECT count(*) FROM Transactions
    #     evaluationOffset: 10
    #   enabled: true
    #   terms:
    #     threshold: 75.0
    #     threshold_occurrences: ALL
    #     threshold_duration: 60
    #     priority: CRITICAL
    #     operator: ABOVE
    #   expiration:
    #     expirationDuration: 360
    #     closeViolationsOnExpiration: false
    #     openViolationOnExpiration: true
    #   violationTimeLimit: ONE_HOUR
    #   valueFunction: SINGLE_VALUE
    #   # Must reference an existing New Relic alert policy from your account
    #   existingPolicyId: 33333333
    #   region: US