{{- if .Values.channel.createChannel }}
{{- if .Values.channel.createChannel.enabled }}
apiVersion: nr.k8s.newrelic.com/v1
kind: AlertsChannel
metadata:
  name: {{ .Values.channel.name }} 
spec:
  api_key: {{ .Values.apiKey }} 
  # api_key_secret:
  #   name: nr-api-key
  #   namespace: default
  #   key_name: api-key
  name: {{ .Values.channel.name }} 
  region: {{ .Values.channel.region }}
  type: {{ .Values.channel.type }} 
  links:
    # Policy links can be by NR PolicyID, NR PolicyName OR K8s AlertPolicy object reference
    policy_ids:
      - 1
    policy_names:
      - {{ .Values.channel.links.policyNames }} 
    policy_kubernetes_objects:
      - name: {{ .Values.channel.links.policyNames }}
        namespace: "default"
  configuration:
    url: {{ .Values.channel.configuration.url }}
{{- end }}
{{- end }}
    