{{- if .Values.channel.createChannel }}
{{- if .Values.channel.createChannel.enabled }}
apiVersion: nr.k8s.newrelic.com/v1
kind: AlertsChannel
metadata:
  annotations:
    helm.sh/hook: post-install
  name: {{ .Values.channel.name }} 
spec:
  api_key: {{ $.Values.apiKey }}
  name: {{ .Values.channel.name | quote }} 
  region: {{ .Values.channel.region | quote }}
  type: {{ .Values.channel.type | quote }}
  links:
  {{- with .Values.channel.links }}
    policy_names: 
    {{- range .policyNames }}
      - {{ . | quote }}
    {{- end }}
  {{- end }}
  configuration:
    url: {{ .Values.channel.configuration.url | quote }}
{{- end }}
{{- end }}
    