# Note: If using a k8s secret, remove `api_key`, uncomment `api_key_secret`,
# add your API key to examples/example_secret.yaml, and run
# `kubectl apply -f examples/example_secret.yaml`
{{- if .Values.alertCondition.createAlertCondition }}
{{- if .Values.alertCondition.createAlertCondition.enabled }}
{{- range .Values.alertCondition.conditions }}
---
apiVersion: nr.k8s.newrelic.com/v1
kind: AlertsNrqlCondition
metadata:
  name: {{ .name }}
spec:
  account_id: {{ $.Values.accountId }}
  {{- if $.Values.alertCondition.secretEnabled }}
  {{- if $.Values.alertCondition.secretEnabled.enabled }}
  {{- with .apiKeySecret }} 
  api_key_secret:
    name: {{ .nrApiKeyName }}
    namespace: {{ .secretNamespace }}
    key_name: {{ .apiKey }}
  {{- end }}
  {{- else }}
  api_key: {{ $.Values.apiKey }}
  {{- end }}
  {{- end }}
  type: {{ .type }}
  {{- with .nrql }}
  nrql:
    query: {{ .query }}
    evaluationOffset: {{ .evaluationOffset }}
  {{- end }}
  enabled: {{ .enabled }}
  {{- with .terms }}
  terms:
    - threshold: {{ .threshold | quote }}
      threshold_occurrences: {{ .threshold_occurrences }}
      threshold_duration: {{ .threshold_duration }}
      priority: {{ .priority }}
      operator: {{ .operator }}
  {{- end }}
  {{- with .expiration }}
  expiration:
    expirationDuration: {{ .expirationDuration }}
    closeViolationsOnExpiration: {{ .closeViolationsOnExpiration }}
    openViolationOnExpiration: {{ .openViolationOnExpiration }}
  {{- end }}
  {{- with .signal }}
  signal:
    aggregation_window: {{ .aggregationWindow }}
    evaluation_offset: {{ .evaluationOffset }}
    fill_option: {{ .fillOption }}
    fill_value: {{ .fillValue }}
  {{- end }}
  name: {{ .name }}
  violationTimeLimit: {{ .violationTimeLimit }}
  valueFunction: {{ .valueFunction }}
  # Must reference an existing New Relic alert policy from your account
  existing_policy_id: {{ .existingPolicyId | quote}}
  region: {{ .region }}
{{- end }}
{{- end }}
{{- end }}
