# Note: If using a k8s secret, remove `api_key`, uncomment `api_key_secret`,
# add your API key to examples/example_secret.yaml, and run
# `kubectl apply -f examples/example_secret.yaml`
{{- if .Values.policy.createPolicy }}
{{- if .Values.policy.createPolicy.enabled }}
apiVersion: nr.k8s.newrelic.com/v1
kind: AlertsPolicy
metadata:
  name: {{ .Values.policy.name }} 
spec:
  account_id: {{ .Values.accountId }}
  api_key: {{ .Values.apiKey }} 
  # api_key_secret:
  #   name: nr-api-key
  #   namespace: default
  #   key_name: api-key
  name: {{ .Values.policy.name }}
  incidentPreference: {{ .Values.policy.incidentPreference }}
  region: {{ .Values.policy.region }}
{{- end }}
{{- end }}