{{- if .Values.policy.createPolicy }}
{{- if .Values.policy.createPolicy.enabled }}
apiVersion: nr.k8s.newrelic.com/v1
kind: AlertsPolicy
metadata:
  name: {{ .Values.policy.name }} 
spec:
  account_id: {{ .Values.accountId }}
  api_key: {{ $.Values.apiKey }}
  name: {{ .Values.policy.name }}
  incidentPreference: {{ .Values.policy.incidentPreference | quote }}
  region: {{ .Values.policy.region | quote }}
  conditions:
  {{- range .Values.policy.conditions }}
    - spec:
        type: {{ .type | quote }}
        {{- with .nrql }}
        nrql:
          query: {{ .query | quote }}
          evaluationOffset: {{ .evaluationOffset }}
        {{- end }}
        enabled: {{ .enabled }}
        {{- with .terms }}
        terms:
          - threshold: {{ .threshold | quote }}
            threshold_occurrences: {{ .threshold_occurrences | quote }}
            threshold_duration: {{ .threshold_duration }}
            priority: {{ .priority | quote }}
            operator: {{ .operator | quote }}
        {{- end }}
        # Expiration section needs more tests 
        # {{- with .expiration }}
        # expiration:
        #   expirationDuration: {{ .expirationDuration }}
        #   closeViolationsOnExpiration: {{ .closeViolationsOnExpiration }}
        #   openViolationOnExpiration: {{ .openViolationOnExpiration }}
        # {{- end }}
        name: {{ .name | quote }}
        violationTimeLimit: {{ .violationTimeLimit | quote }}
        valueFunction: {{ .valueFunction | quote }}
  {{- end }}
{{- end }}
{{- end }}